openapi: 3.0.0
info:
  title: API Ping
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Retourne "pong"
      responses:
        '200':
          description: Réponse réussie
          content:
            text/plain:
              schema:
                type: string
                example: pong