openapi: 3.0.3
info:
  title: API Recherche de Produits
  version: 1.0.0
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: "Laptop"
        expiration:
          type: string
          format: date-time
          example: "2025-12-31T23:59:59Z"
        price:
          type: number
          format: decimal
          example: 999.99
      required:
        - name
        - expiration
        - price
  parameters:
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        example: 10
      description: Nombre maximum d'éléments
    q:
      name: q
      in: query
      required: false
      schema:
        type: string
        example: "laptop"
      description: Terme de recherche
paths:
  /products:
    get:
      summary: Récupère une liste de produits
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/q'
      responses:
        '200':
          description: Liste de produits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multipleProducts:
                  value:
                    - { "name": "Laptop", "expiration": "2025-12-31T23:59:59Z", "price": 999.99 }
                    - { "name": "Smartphone", "expiration": "2026-06-15T23:59:59Z", "price": 499.99 }
                emptyList:
                  value: []